# Reading in MCTS (Monte Carlo Tree Search) data
### The goal is to train two RNNs.
 - Predict Probability of each of the moves being successful
 - Evaluate the value of the current board position

In [1]:
# uninstall numpy and then reinstall/update tensorflow
import pandas as pd
import numpy as np
print(np.__version__) # must not be the most recent. 1.26.4 works.
import tensorflow as tf
print(tf.__version__)
  
from board import Board
import math
import pickle
import gzip

1.26.4
2.18.0-dev20240717


In [2]:
def loadall(filename, n=math.inf):
    data = []
    with gzip.open(filename, "rb", compresslevel=9) as f:
        while len(data) < n:
            try:
                df = pickle.load(f)
                data.append(df)
            except EOFError:
                break
            
            print(len(data))
            
    return data

In [29]:
import pandas as pd 
print(pd.__version__) # should work with 2.2.2
from board import Board

df_total = pd.DataFrame()

items = loadall('Data/playing_data_saved.pkl')
for value in items:
    df_total = pd.concat([df_total, value])
print(df_total.shape, ' shape')

# items = loadall('Data/playing_data_saved.pkl')
# for value in items:
#     df_total = pd.concat([df_total, value])    
# print(df_total.shape, ' shape')

# items = loadall('Data/playing_data_saved1.pkl')
# for value in items:
#     df_total = pd.concat([df_total, value])
# print(df_total.shape, ' shape')

# items = loadall('Data/playing_data.pkl')
# for value in items:
#     df_total = pd.concat([df_total, value])


print(df_total.shape, ' shape')
print(df_total.size, ' size')

2.2.2
1
(165335, 8)  shape
(165335, 8)  shape
1322680  size


In [30]:
print(df_total.columns)

Index(['Board', 'Moves', 'Move_Probs', 'Reward', 'Weights', 'Num_Sims',
       'mc_type', 'inv_left'],
      dtype='object')


In [26]:
# checking out to make the data is stored correctly
  
for i in range(20):
    print(i, df_total.iloc[i]['Move_Probs'])
    # x = df_total.iloc[i]['Board']
    # board = Board(14)
    # board.show_dots = False
    # board.board = x
    # print(board)



0 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [60]:
import copy


all_poss_moves = []
for x in range(14):
  for y in range(14):
     for piece in range(21):
        for orient in range(8):
           all_poss_moves.append([x,y,piece, orient])
         
print(len(all_poss_moves))
changed_df = df_total.copy()
changed_df = changed_df.drop('Move_Probs', axis=1)

print('cloning done', changed_df.head)
row_num = 0
for index, row in df_total.iterrows():
    if row_num < 10:
        print(index, row_num)
        row_num += 1
        moves_probs = []
        hist_moves = row['Moves']
        hist_moves_probs = row['Move_Probs']
        for poss_move in all_poss_moves:
            if poss_move in hist_moves:
                index = hist_moves.index(poss_move)
                moves_probs.append(hist_moves_probs[index])
            else:
                moves_probs.append(0)
        print(len(moves_probs))
        print(moves_probs[:10])
        
        changed_df.iloc[index]['Move_Probs'] = np.array(moves_probs)
        print(len(changed_df.iloc[index]['Move_Probs']))
    else:
        break
    

32928
cloneing done <bound method NDFrame.head of                                                 Board  \
0   [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [...   
1   [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [...   
2   [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [...   
3   [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [...   
4   [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [...   
..                                                ...   
55  [[0, 0, 0, 0, 1, 1, 0, 0, 1, 0, -1, -1, -1, -1...   
56  [[0, 0, 0, 0, 1, 1, 0, 0, 1, 0, -1, -1, -1, -1...   
57  [[-1, 0, 0, 0, 1, 1, 0, 0, 1, 0, -1, -1, -1, -...   
58  [[-1, 0, 0, 0, 1, 1, 0, 0, 1, 0, -1, -1, -1, -...   
59  [[-1, 0, 0, 0, 1, 1, 0, 0, 1, 0, -1, -1, -1, -...   

                                                Moves  Reward  \
0   [[3, 5, 9, 1, 0, 1], [4, 4, 20, 0, 0, 0], [3, ...      -1   
1   [[10, 8, 11, 7, 0, 1], [9, 11, 7, 1, 0, 0], [1...       1   
2   [[6, 3, 6, 1, 0, 2], [5, 6, 0, 0, 1, 0], [5, 8...      -1   
3   [

C:\Users\jjfri\AppData\Local\Temp\ipykernel_23068\2184936085.py:32: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  changed_df.iloc[index]['Move_Probs'] = np.array(moves_probs)
C:\Users\jjfri\AppData\Local\Temp\ipykernel_23068\2184936085.py:32: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  changed_df.iloc[index]['Move_Probs'] = np.array(moves_probs)


KeyError: 'Move_Probs'

In [59]:
x = changed_df.iloc[0]['Move_Probs']
print(len(x))
# print(total_df.head)
print(changed_df.head)

508
<bound method NDFrame.head of                                                 Board  \
0   [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [...   
1   [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [...   
2   [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [...   
3   [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [...   
4   [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [...   
..                                                ...   
55  [[0, 0, 0, 0, 1, 1, 0, 0, 1, 0, -1, -1, -1, -1...   
56  [[0, 0, 0, 0, 1, 1, 0, 0, 1, 0, -1, -1, -1, -1...   
57  [[-1, 0, 0, 0, 1, 1, 0, 0, 1, 0, -1, -1, -1, -...   
58  [[-1, 0, 0, 0, 1, 1, 0, 0, 1, 0, -1, -1, -1, -...   
59  [[-1, 0, 0, 0, 1, 1, 0, 0, 1, 0, -1, -1, -1, -...   

                                                Moves  \
0   [[3, 5, 9, 1, 0, 1], [4, 4, 20, 0, 0, 0], [3, ...   
1   [[10, 8, 11, 7, 0, 1], [9, 11, 7, 1, 0, 0], [1...   
2   [[6, 3, 6, 1, 0, 2], [5, 6, 0, 0, 1, 0], [5, 8...   
3   [[11, 5, 7, 0, 0, 2], [10, 10, 20, 4, 2, 3], [...

In [39]:
file_name = 'fixed_games.pkl'
with gzip.open(file_name, "wb", compresslevel=9) as f:
  print(changed_df.shape)
  try:
    pickle.dump(changed_df, f)
  except:
      print("couldn't save the hour")
      pass

print('finial save : ', file_name)

(165335, 8)
finial save :  fixed_games.pkl


# Working on the DCNNs
### References:
 - https://medium.com/aiguys/deep-convolutional-neural-networks-dcnns-explained-in-layman-terms-b990b2818061
  - https://nikcheerla.github.io/deeplearningschool/2018/01/01/AlphaZero-Explained/


In [3]:
import pandas as pd

df_total = pd.DataFrame()

# items = loadall('Data/playing_data_saved.pkl')
# for value in items:
#     df_total = pd.concat([df_total, value])
    
# print(df_total.shape)

looking = True
i = 0

while looking:
    i += 1
    try:
        load_filename = "Data/7-24/t" + str(i) + '.pkl'
        
        print(load_filename)
        items = loadall(load_filename)
        
        for value in items:
            df_total = pd.concat([df_total, value])
            
        print(df_total.shape)
    except:
        looking = False
        print(i)
        break
    
print(df_total.shape, "shape")


# df_total = pd.DataFrame()

# load_filename = "Data/21.pkl"
        
# print(load_filename)
# items = loadall(load_filename)

# for value in items:
#     df_total = pd.concat([df_total, value])

    
# print(df_total.shape, "shape")
            

Data/7-24/t1.pkl
1
(7472, 8)
Data/7-24/t2.pkl
1
(14950, 8)
Data/7-24/t3.pkl
1
(22074, 8)
Data/7-24/t4.pkl
1
(30178, 8)
Data/7-24/t5.pkl
1
(38132, 8)
Data/7-24/t6.pkl
1
(45756, 8)
Data/7-24/t7.pkl
1
(53924, 8)
Data/7-24/t8.pkl
1
(61294, 8)
Data/7-24/t9.pkl
1
(68872, 8)
Data/7-24/t10.pkl


In [ ]:
for i in range(57):
    print(df_total.iloc[i])

Board         [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [...
Moves         [[3, 4, 20, 7], [3, 4, 5, 5], [4, 5, 14, 4], [...
Move_Probs    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Reward                                                        1
Weights       [5.915347541427181, 28.800744522175954, 51.914...
Num_Sims                                                    943
mc_type                                              monteCarlo
inv_left                                             [6, 7, 12]
Name: 0, dtype: object
Board         [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [...
Moves         [[10, 9, 9, 0], [8, 9, 5, 1], [9, 9, 1, 1], [8...
Move_Probs    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Reward                                                       -1
Weights       [5.915347541427181, 28.800744522175954, 51.914...
Num_Sims                                                    943
mc_type                                              monteCarlo
inv_left         

In [ ]:
def preprocess_data(games, train_test_ratio=.8):
    # Convert game records into input-output pairs
    games = games.sample(frac = 1)
    split_index = math.floor(train_test_ratio*(games.shape[0]))
    sameation_num = 10
    print("Amount of training batches: ", split_index)
    train_df = games.iloc[:split_index-sameation_num]
    test_df = games.iloc[split_index:]
    sameation_df = games.iloc[split_index-sameation_num:split_index]

    train_boards = np.array(tuple(train_df['Board'].values))
    train_rewards = np.array(tuple(train_df['Reward'].values))
    train_moves = np.array(tuple(train_df['Move_Probs'].values))

    test_boards = np.array(tuple(test_df['Board'].values))
    test_rewards = np.array(tuple(test_df['Reward'].values))
    test_moves = np.array(tuple(train_df['Move_Probs'].values))
    
    x_val = np.array(tuple(sameation_df['Board'].values))
    y_val_reward = np.array(tuple(sameation_df['Reward'].values))
    y_val_moves = np.array(tuple(train_df['Move_Probs'].values))
    
    print(train_moves.shape)
    train_boards = np.reshape(train_boards, (train_boards.shape[0], train_boards.shape[1], train_boards.shape[2], 1))
    train_moves = np.reshape(train_moves, (train_moves.shape[0], train_moves.shape[1], train_moves.shape[2], 1))

    
    processed_data = {
        "train boards": train_boards,
        "train rewards": train_rewards,
        "train moves": train_moves,
        "test boards": test_boards,
        "test rewards": test_rewards,
        "test moves": test_moves,
        "x val": x_val,
        "y val rewards": y_val_reward,
        "y val moves": y_val_moves
    }
    
    # Normalize and format the data for training
    return processed_data

In [ ]:
# Defining the evaluation snd predictive networks
def create_policy_network(input_shape):
    model = tf.keras.Sequential([
        tf.keras.layers.Conv2D(32, kernel_size=3, activation='relu', input_shape=input_shape),
        tf.keras.layers.Conv2D(64, kernel_size=3, activation='relu'),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(256, activation='relu'),
        tf.keras.layers.Dense(14*14*21*8, activation='softmax')
    ])
    return model

def create_policy_network_v2(input_shape):
    model = tf.keras.Sequential([
        # 1st conv
        tf.keras.layers.Conv2D(filters = 96, input_shape = input_shape,  
                kernel_size = (5, 5),  strides = (4,4),
                padding = 'same'),
        tf.keras.layers.Activation('relu'),
        tf.keras.layers.MaxPooling2D(pool_size = (2, 2), 
                    strides = (2, 2), padding = 'same'),
        tf.keras.layers.BatchNormalization(), 
        
        # 2nd Convolutional Layer 
        tf.keras.layers.Conv2D(filters = 30, kernel_size = (6, 6),  
                    strides = (1, 1), padding = 'same'), 
        tf.keras.layers.Activation('relu'), 
        tf.keras.layers.MaxPooling2D(pool_size = (2, 2),  
                    padding = 'same'),
        tf.keras.layers.BatchNormalization(),
        
        # 3rd Convolutional Layer 
        tf.keras.layers.Conv2D(filters = 384, kernel_size = (3, 3),  
                    strides = (1, 1), padding = 'same'),
        tf.keras.layers.Activation('relu'),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Flatten(),
    
        # 1st Dense Layer 
        tf.keras.layers.Dense(4096, input_shape = (14*14*1, )),
        tf.keras.layers.Activation('relu'),
        # Add Dropout to prevent overfitting 
        tf.keras.layers.Dropout(0.3),
        # Batch Normalisation 
        tf.keras.layers.BatchNormalization(),
        
        # 2nd Dense Layer
        tf.keras.layers.Dense(20480, input_shape = (14*14*1, )),
        tf.keras.layers.Activation('relu'),
        # Add Dropout to prevent overfitting 
        tf.keras.layers.Dropout(0.3),
        # Batch Normalisation 
        tf.keras.layers.BatchNormalization(),
        
        # 3rd Dense Layer 
        tf.keras.layers.Dense(40960),
        tf.keras.layers.Activation('relu'),
        # Add Dropout 
        tf.keras.layers.Dropout(0.2),
        # Batch Normalisation 
        tf.keras.layers.BatchNormalization(),
        
        #output
        tf.keras.layers.Dense(14*14*21*8, activation='softmax')
    ])
    return model

def create_value_network(input_shape):
    model = tf.keras.Sequential([
        tf.keras.layers.Conv2D(32, kernel_size=6, activation='relu', input_shape=input_shape, padding='same'),
        tf.keras.layers.BatchNormalization(), 
        tf.keras.layers.Conv2D(128, kernel_size=6, activation='relu', padding='valid'),
        tf.keras.layers.BatchNormalization(), 
        tf.keras.layers.Conv2D(64, kernel_size=3, activation='relu', padding='valid'),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(4096, input_shape = (14*14*1, )),
        tf.keras.layers.Activation('relu'),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Dense(4096),
        tf.keras.layers.Activation('relu'),
        tf.keras.layers.Dropout(0.4),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Dense(2048),
        tf.keras.layers.Activation('relu'),
        tf.keras.layers.Dropout(0.4),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Dense(1, activation='tanh')
    ])
    return model


def create_value_network1(input_shape):
    model = tf.keras.Sequential([

        tf.keras.layers.Conv2D(filters = 96, input_shape = input_shape,  
                    kernel_size = (5, 5),  strides = (4,4),
                    padding = 'same'),
        tf.keras.layers.Activation('relu'),
        # Max-Pooling  
        tf.keras.layers.MaxPooling2D(pool_size = (2, 2), 
                    strides = (2, 2), padding = 'same'),
        # # Batch Normalisation 
        tf.keras.layers.BatchNormalization(), 
        
        # 2nd Convolutional Layer 
        tf.keras.layers.Conv2D(filters = 30, kernel_size = (6, 6),  
                    strides = (1, 1), padding = 'same'), 
        tf.keras.layers.Activation('relu'), 
        # Max-Pooling 
        tf.keras.layers.MaxPooling2D(pool_size = (2, 2),  
                    padding = 'same'),
        # Batch Normalisation 
        tf.keras.layers.BatchNormalization(),
        
        # 3rd Convolutional Layer 
        tf.keras.layers.Conv2D(filters = 384, kernel_size = (3, 3),  
                    strides = (1, 1), padding = 'same'),
        tf.keras.layers.Activation('relu'),
        # Batch Normalisation 
        tf.keras.layers.BatchNormalization(),
        
        # # 4th Convolutional Layer 
        # tf.keras.layers.Conv2D(filters = 384, kernel_size = (3, 3),  
        #             strides = (1, 1), padding = 'same'),
        # tf.keras.layers.Activation('relu'),
        # # Batch Normalisation 
        # tf.keras.layers.BatchNormalization(),
        
        # # 5th Convolutional Layer 
        # tf.keras.layers.Conv2D(filters = 256, kernel_size = (3, 3),  
        #             strides = (1, 1), padding = 'same'),
        # tf.keras.layers.Activation('relu'),
        # # Max-Pooling 
        # tf.keras.layers.MaxPooling2D(pool_size = (2, 2), strides = (2, 2),  
        #             padding = 'same'),
        # # Batch Normalisation 
        # tf.keras.layers.BatchNormalization(),
        
        # Flattening 
        tf.keras.layers.Flatten(),
        
        # 1st Dense Layer 
        tf.keras.layers.Dense(4096, input_shape = (14*14*1, )),
        tf.keras.layers.Activation('relu'),
        # Add Dropout to prevent overfitting 
        tf.keras.layers.Dropout(0.5),
        # Batch Normalisation 
        tf.keras.layers.BatchNormalization(),
        
        # 2nd Dense Layer 
        tf.keras.layers.Dense(4096),
        tf.keras.layers.Activation('relu'),
        # Add Dropout 
        tf.keras.layers.Dropout(0.5),
        # Batch Normalisation 
        tf.keras.layers.BatchNormalization(),
        
        model.add(tf.keras.layers.Dense(1)) ,
        model.add(tf.keras.layers.Activation('sigmoid'))
    ])
    return model

def create_value_network_AlexNet(input_shape):
    model = tf.keras.Sequential() 
    # 1st Convolutional Layer 
    model.add(tf.keras.layers.Conv2D(filters = 32, input_shape = input_shape,  
                kernel_size = (6, 6), strides = (2, 2),  
                padding = 'valid')) 
    model.add(tf.keras.layers.Activation('relu')) 
    # Max-Pooling  
    # model.add(tf.keras.layers.MaxPooling2D(pool_size = (2, 2), 
    #             strides = (2, 2), padding = 'valid')) 
    # Batch Normalisation 
    model.add(tf.keras.layers.BatchNormalization()) 
    
    # 2nd Convolutional Layer 
    model.add(tf.keras.layers.Conv2D(filters = 64, kernel_size = (4, 4),  
                strides = (1, 1), padding = 'valid')) 
    model.add(tf.keras.layers.Activation('relu')) 
    # Max-Pooling 
    # model.add(tf.keras.layers.MaxPooling2D(pool_size = (2, 2), strides = (2, 2),  
    #             padding = 'valid')) 
    # Batch Normalisation 
    model.add(tf.keras.layers.BatchNormalization()) 
    
    # 3rd Convolutional Layer 
    model.add(tf.keras.layers.Conv2D(filters = 64, kernel_size = (3, 3),  
                strides = (1, 1), padding = 'same')) 
    model.add(tf.keras.layers.Activation('relu')) 
    # Batch Normalisation 
    model.add(tf.keras.layers.BatchNormalization()) 
    
    # 4th Convolutional Layer 
    model.add(tf.keras.layers.Conv2D(filters = 84, kernel_size = (3, 3),  
                strides = (1, 1), padding = 'same')) 
    model.add(tf.keras.layers.Activation('relu')) 
    # Batch Normalisation 
    model.add(tf.keras.layers.BatchNormalization()) 
    
    # 5th Convolutional Layer 
    model.add(tf.keras.layers.Conv2D(filters = 32, kernel_size = (3, 3),  
                strides = (1, 1), padding = 'same')) 
    model.add(tf.keras.layers.Activation('relu')) 
    # Max-Pooling 
    model.add(tf.keras.layers.MaxPooling2D(pool_size = (2, 2), strides = (2, 2),  
                padding = 'valid')) 
    # Batch Normalisation 
    model.add(tf.keras.layers.BatchNormalization()) 
    
    # Flattening 
    model.add(tf.keras.layers.Flatten()) 
    
    # 1st Dense Layer 
    model.add(tf.keras.layers.Dense(4096, input_shape = (14*14*1, ))) 
    model.add(tf.keras.layers.Activation('relu')) 
    # Add Dropout to prevent overfitting 
    model.add(tf.keras.layers.Dropout(0.4)) 
    # Batch Normalisation 
    model.add(tf.keras.layers.BatchNormalization()) 
    
    # 2nd Dense Layer 
    model.add(tf.keras.layers.Dense(4096)) 
    model.add(tf.keras.layers.Activation('relu')) 
    # Add Dropout 
    model.add(tf.keras.layers.Dropout(0.4)) 
    # Batch Normalisation 
    model.add(tf.keras.layers.BatchNormalization()) 
    
    # Output Softmax Layer 
    model.add(tf.keras.layers.Dense(1)) ,
    model.add(tf.keras.layers.Activation('sigmoid'))
    
    return model 

In [ ]:
# Code snippet for training the neural networks
def compile_networks(policy_network, value_network):
    # Define loss functions and optimizer
    policy_loss = tf.keras.losses.CategoricalCrossentropy()
    value_loss = tf.keras.losses.MeanSquaredError()
    optimizer = tf.keras.optimizers.Adam()
    metrics = [tf.keras.metrics.SparseCategoricalAccuracy()]

    # Compile the models
    policy_network.compile(optimizer=optimizer, loss=policy_loss, metrics=metrics)
    value_network.compile(optimizer=optimizer, loss=value_loss, metrics=metrics)

def train_networks(policy_network, value_network, data, epochs=10, batch_size=64):
    # Train the models
    policy_network.fit(data['train boards'], data['train moves'], epochs=epochs, batch_size=batch_size, validation_data=(data["x val"], data["y val moves"]), verbose=2)
    # value_network.fit(data['train boards'], data['train rewards'], epochs=epochs, batch_size=batch_size, validation_data=(data['x val'], data['y val rewards']), verbose=2)
    

In [21]:
# # t1 has been fitted
# df_total = pd.DataFrame()

# load_filename = "Data/data_prob_moves_wrong/t1.pkl"
        
# print(load_filename)
# items = loadall(load_filename)

# for value in items:
#     df_total = pd.concat([df_total, value])

    
# print(df_total.shape, "shape")

Data/data_prob_moves_wrong/t1.pkl
1
(285722, 8) shape


In [13]:
# from tensorflow.python.client import device_lib

# tf.config.list_physical_devices('GPU')
# print(device_lib.list_local_devices())


# print(df_total.iloc[1]["Reward"])
# print(df_total.iloc[2]["Reward"])


[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 17784568953891093317
xla_global_id: -1
]
1
-1


In [ ]:
print(np.shape(df_total))
data = preprocess_data(df_total, train_test_ratio=.8)
print(np.shape(data["train boards"])[0])

In [22]:
board_size = 14
input_shape = (board_size, board_size, 1)

strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
    policy_network = create_policy_network_v2(input_shape)
    value_network = create_value_network(input_shape)
    # value_network = create_value_network_AlexNet(input_shape)

    # value_net_path = "models/value_net_basic.keras" # has been trained on t1 and t21
    # value_network = tf.keras.models.load_model(value_net_path)
    # value_network.summary()
    
    compile_networks(policy_network, value_network)

train_networks(policy_network, value_network, data, epochs=10, batch_size=64)

(112872, 8)


In [11]:
to_pred = np.array((tuple(df_total.iloc[14]['Board'])))
to_pred = to_pred[np.newaxis, :, :, np.newaxis]
print(np.shape(to_pred), df_total.iloc[14]['Reward'])
value_network.predict(to_pred)

(1, 14, 14, 1) -1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step


array([[1.]], dtype=float32)

In [12]:
# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = value_network.evaluate(data['test boards'], data['test rewards'], batch_size=12)
print("test loss, test acc:", results)

# Generate predictions (probabilities -- the output of the last layer)
# on new data using `predict`
for i in range(20):
    # print("Generate predictions for 3 samples")
    to_pred = np.array(tuple(data['test boards'][i]))
    print(to_pred)
    print(data['test rewards'][i])
    to_pred = to_pred[np.newaxis, :, :, np.newaxis]

    predictions = value_network.predict(to_pred)
    print("predictions shape:", predictions.shape)
    print("prediction:", predictions, "correct reward: ", data['test rewards'][i])

# previous was acc: 0.248

Evaluate on test data
10342/10342 ━━━━━━━━━━━━━━━━━━━━ 76s 7ms/step - loss: 0.9657 - sparse_categorical_accuracy: 0.0235
test loss, test acc: [0.9667264223098755, 0.02275712601840496]
[[ 0  0  0  0  0  0  1  0  1  1  0  0  0  0]
 [ 0  0  0 -1  0  0  1  0  1  1  0  0  0  0]
 [ 0  0  0 -1 -1  0  1  1  0  1  0  0  0  0]
 [ 0  0  0  0 -1  0  0  1  0  0  0  1  0  0]
 [ 0  0  0  0 -1  0  1  0  0  0  1  1  1  0]
 [ 0 -1  0 -1  0  0  1  0  0  0  0  0  1  0]
 [ 0 -1  0 -1 -1 -1  1  1  1  0  1  1  0  0]
 [ 0 -1 -1  0 -1  0  0  0  0  1  0  1  0  0]
 [ 0  0  0  0  0 -1 -1  0  1  1  1  0  0  0]
 [ 0  0  0  0  0  0 -1  0  0  1  0  0  0  0]
 [ 0 -1  0  0  0 -1 -1  0  1  0  0  0  0  0]
 [ 0 -1  0  0 -1  0  1  1  1  0 -1 -1 -1  0]
 [-1 -1  0 -1 -1  0  0  0  1  0 -1 -1  0  0]
 [-1  0 -1 -1  0 -1 -1 -1 -1 -1  0  0  0  0]]
-1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
predictions shape: (1, 1)
prediction: [[0.06263743]] correct reward:  -1
[[ 0  0  0  0  0  1  1  1  0  1  0  1  1  0]
 [ 0  0 -1 -1 -1  1  0  0 

In [14]:
import tensorflow as tf

value_net_path = "models/value_net_basic.keras"
value_network.save(value_net_path)

In [15]:
value_network_saved = tf.keras.models.load_model(value_net_path)
value_network_saved.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_2 (Conv2D)               │ (None, 14, 14, 32)     │         1,184 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 14, 14, 32)     │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 9, 9, 128)      │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 9, 9, 128)      │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 7, 7, 64)       │        73,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 3136)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 4096)           │    12,849,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation (Activation)         │ (None, 4096)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 4096)           │        16,384 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 4096)           │    16,781,312 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_1 (Activation)       │ (None, 4096)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 4096)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 4096)           │        16,384 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 2048)           │     8,390,656 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_2 (Activation)       │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 2048)           │         8,192 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │         2,049 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 114,820,389 (438.01 MB)

 Trainable params: 38,266,529 (145.98 MB)

 Non-trainable params: 20,800 (81.25 KB)

 Optimizer params: 76,533,060 (291.95 MB)